name: Detox E2E CI

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      prNumber:
        description: pr number to trigger on
        required: true

jobs:
  # prepare-test-run:
  #   name: "Prepare test run"
  #   runs-on: macos-latest
  #   steps:
  #     - name: prepare runner
  #       run: 

  ios:
    # needs: [prepare-test-run]
    runs-on: macos-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
      
      - name: List sims
        run: applesimutils --list

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          # node-version: '14'
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Has hash commit deps
        uses: ledgerhq/actions/packages/has-hash-commit-deps@main
        id: has-hash-commit-deps
        with:
          workspace: ${{ github.workspace }}

      - name: Install dependencies 
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'true' }}
        env:
          JOBS: max
        run: yarn --prefer-offline --frozen-lockfile --network-timeout 100000 --network-concurrency 1

      - name: Install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'false' }}
        env:
          JOBS: max
        run: yarn --prefer-offline --frozen-lockfile --network-timeout 100000    

      # - name: Rebuild detox
      #   if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
      #   run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Build iOS app for detox test run
        env:
          NODE_OPTIONS: "--max-old-space-size=7168"
        run: yarn e2e:build -c ios.staging

      - name: Test iOS app
        timeout-minutes: 15
        run: yarn e2e:test -c ios.staging --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing
#  --retries 1 --reuse
        
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-ios-artifacts
          path: artifacts
        
  android:
    runs-on: macos-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Check hash commit deps
        uses: ledgerhq/actions/packages/has-hash-commit-deps@main
        id: has-hash-commit-deps
        with:
          workspace: ${{ github.workspace }}

      - name: Install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'true' }}
        env:
          JOBS: max
        run: yarn --prefer-offline --frozen-lockfile --network-timeout 100000 --network-concurrency 1

      - name: install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'false' }}
        env:
          JOBS: max
        run: yarn --prefer-offline --frozen-lockfile --network-timeout 100000   

      # - name: Gradle cache
      #   uses: gradle/gradle-build-action@v2
        
      # - name: AVD cache
      #   uses: actions/cache@v2
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/adb*
      #     key: avd-api-29
      
      - name: Build Android app for Detox test run
        env:
          NODE_OPTIONS: "--max-old-space-size=7168"
        run: yarn e2e:build -c android.staging 

      - name: Run Android tests
        timeout-minutes: 15
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          # force-avd-creation: false
          avd-name: Nexus_6_API_30
          emulator-options: -verbose -no-boot-anim -noaudio
          ram-size: 2048
          # disable-animations: true
          script: |
            adb logcat -c
            adb logcat *:E &
            $ANDROID_HOME/platform-tools/adb devices
            yarn e2e:test -c android.staging --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing
        # yarn start & yarn detox test -c android.debug --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing
        # mkdir ./temp
        # curl -f -o ./temp/test-butler-app.apk https://repo1.maven.org/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.apk
        # adb install ./temp/test-butler-app.apk || adb install ./e2e/test-butler-app.apk
        # adb logcat -c
        # adb logcat *:E &

      # - name: Run Android tests (with Test Butler)
      #   if: steps.avd-cache.outputs.cache-hit == 'true'
      #   timeout-minutes: 30
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 30
      #     # force-avd-creation: false
      #     avd-name: Nexus_6_API_30
      #     emulator-options: -verbose -no-snapshot-save -no-boot-anim -noaudio
      #     ram-size: 2048
      #     # disable-animations: true
      #     # ./gradlew connectedCheck
      #     script: |
      #       adb logcat -c
      #       adb logcat *:E &
      #       mkdir ./temp
      #       curl -f -o ./temp/test-butler-app.apk https://repo1.maven.org/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.apk
      #       adb install ./temp/test-butler-app.apk || adb install ./e2e/test-butler-app.apk
      #       yarn start & yarn detox test -c android.debug --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing
#  --retries 1 --reuse

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-android-artifacts
          path: artifacts
